export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_FAILURE = "LOGIN_ADMIN_FAILURE";

export const ADMIN_AUTH_SUCCESS = "ADMIN_AUTH_SUCCESS";
export const ADMIN_AUTH_FAILURE = "ADMIN_AUTH_FAILURE";

export const LOGOUT_ADMIN_SUCCESS = "LOGOUT_ADMIN_SUCCESS";
export const LOGOUT_ADMIN_FAILURE = "LOGOUT_ADMIN_FAILURE";

export const ADD_STAFF_REQUEST = "ADD_STAFF_REQUEST";
export const ADD_STAFF_SUCCESS = "ADD_STAFF_SUCCESS";
export const ADD_STAFF_FAILURE = "ADD_STAFF_FAILURE";

export const EMPTY_SUCCESS_MESSAGE = "EMPTY_SUCCESS_MESSAGE";
export const EMPTY_FAILURE_MESSAGE = "EMPTY_FAILURE_MESSAGE";